ktor {
    deployment {
        port = 8080
    }
    application {
        modules = [ com.studentplanner.ApplicationKt.module ]
    }
}

mongo {
    connectionString = ${?MONGO_URI}
    databaseName = ${?MONGO_DB_NAME}
}
